import dotenv from "dotenv";
/**
 * `path` is Node.js's built-in module for working with file system paths.
 * We use it to figure out where the .env file actually lives on disk.
 */
import path from "node:path";

/**
 * `fileURLToPath` is a utility that converts a file URL (something like
 * `file:///Users/ramkrishnayadav/ai-engineering/src/utils/getEnv.ts`) into
 * a normal file path (`/Users/ramkrishnayadav/ai-engineering/src/utils/getEnv.ts`).
 *
 * We need this because in modern ESM (ECMAScript Modules, which TypeScript/JS
 * uses when you `import`), the location of the current file is given as a URL,
 * not as a plain path. `path.dirname()` below can't work with a URL, so we
 * convert it first.
 */
import { fileURLToPath } from "node:url";

/**
 * `import.meta.url` is a special value that holds the URL of the CURRENT file
 * being executed (in this case, this getEnv.ts file). It's automatically
 * generated by the compiler.
 *
 * This is exactly like `__filename` in older CommonJS Node.js code, but the
 * ESM-style version.
 */
const currentFile = fileURLToPath(import.meta.url);

/**
 * `path.dirname()` takes a full file path and returns just the directory part.
 *
 * For this file, `currentFile` would be:
 *   /Users/ramkrishnayadav/ai-engineering/src/utils/getEnv.ts
 *
 * So `currentDirectory` becomes:
 *   /Users/ramkrishnayadav/ai-engineering/src/utils
 *
 * In short: this tells us "we are running inside the src/utils folder".
 */
const currentDirectory = path.dirname(currentFile);

/**
 * `dotenv.config()` starts reading the .env file.
 *
 * The `{ path: ... }` option is IMPORTANT: it tells dotenv EXACTLY where to
 * look. Without it, dotenv uses a bunch of default locations, and in a
 * monorepo/complex folder structure those defaults might not be right.
 *
 * `path.resolve(currentDirectory, "../../.env")` builds the full path:
 *   currentDirectory = .../src/utils          (the folder of this file)
 *   ../../                                        (go up two levels)
 *          -> .../src/utils/../../  =  .../
 *   .env                                          (add the .env file name)
 *
 * Resulting path: /Users/ramkrishnayadav/ai-engineering/.env  (the project root)
 *
 * We use `path.resolve(...)` instead of writing the path by hand, because
 * it works no matter where the project is installed on any computer. If someone
 * moves the folder, the code still finds .env because it always starts from
 * THIS file's location and walks up two levels.
 */
dotenv.config({
  path: path.resolve(currentDirectory, "../../.env"),
});

// ---------------------------------------------------------------------------
// Step 2: Export a clean object with all variables
// ---------------------------------------------------------------------------

/**
 * `env` is the object you import from anywhere in your app.
 *
 * How to use it:
 *   import { env } from './utils/getEnv';
 *
 *   const apiKey = env.GEMINI_API_KEY;       // -> "AQ.Ab8RN6Kc_..." or undefined
 *   const dbUrl  = env.DATABASE_URL;          // -> "postgresql://..." or undefined
 *
 * The values are whatever is currently in `process.env` for that name. If a
 * variable is missing from your .env file, the value will be `undefined` -
 * nothing special happens automatically, so make sure all required variables
 * are actually set in .env.
 */
export const env = {
  /** AI MODEL - the API keys for the two AI model providers */
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,

  /** AI MODEL - which model to use */
  EMBEDDING_MODEL: process.env.EMBEDDING_MODEL,
  CHAT_MODEL: process.env.CHAT_MODEL,

  /** DATABASE URL - connection string for the PostgreSQL database */
  DATABASE_URL: process.env.DATABASE_URL,

  /** LANGSMITH - tracing/observability settings */
  LANGSMITH_TRACING: process.env.LANGSMITH_TRACING,
  LANGSMITH_ENDPOINT: process.env.LANGSMITH_ENDPOINT,
  LANGSMITH_API_KEY: process.env.LANGSMITH_API_KEY,
  LANGSMITH_PROJECT: process.env.LANGSMITH_PROJECT,

  /** BETTER AUTH - authentication settings */
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,

  /** S3 OBJECT STORAGE - cloud storage settings */
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
  S3_API: process.env.S3_API,
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
  S3_TOKEN_VALUE: process.env.S3_TOKEN_VALUE,
  S3_BUCKET: process.env.S3_BUCKET,
  S3_PUBLIC_DEPLOYMENT_URL: process.env.S3_PUBLIC_DEPLOYMENT_URL,
  //ATLASV1 REDIS
  ATLASV1_REDIS__REST_URL: process.env.ATLASV1_REDIS__REST_URL,
  ATLASV1_REDIS_TOKEN: process.env.ATLASV1_REDIS_TOKEN,
  ATLASV1_REDIS_CONNECTION_URL:process.env.ATLASV1_REDIS_CONNECTION_URL
};
